### PR TITLE
Reformat README json to use 2 space indents

### PR DESCRIPTION
**Pull request by Xerkus**
Json in README code blocks is displayed in browser with 8-wide tabs which makes it hard to read.

This PR reformats them to use 2 space indents instead.

### CODE REVIEW

**Comment by RussellLuo** [comment]
FYI, this seems to be the same issue as https://github.com/mholt/caddy-ratelimit/issues/1.

**Comment by Xerkus** [comment]
Many editors support editor config

`.editorconfig` file in the root might be picked up by the editor automatically:

```
[README.md]
indent_style = space
indent_size = 2
```

**Comment by mholt** [comment]
Tab width is a rendering preference. GitHub and other editors let you customize the width, and I'm not interested in changing to spaces because everyone has different opinions on this, but at least tabs let each user configure them.

**Comment by Xerkus** [comment]
It was not about the editor. It is about what you see when you open the repository web page page. First thing you see, pretty much.

Readme screenshot

**Comment by mholt** [comment]
If you've changed your tab width settings on GitHub to 2 and it's still rendering them as 8-wide, then that's probably a bug in GitHub...

**Comment by Xerkus** [comment]
Checked css, github does set tab-size css for code files but not for `<pre>` tag in rendered html from markdown.
Does the setting work for you there? I guess I can try to send bug report to github.

**Comment by francislavoie** [comment]
As I've said in the other thread https://github.com/mholt/caddy-ratelimit/issues/1#issuecomment-810534882, I use the https://github.com/sindresorhus/refined-github browser plugin which does fix this. But yeah, it would make sense to ask Github to fix this.

**Pull request closed without merging**
