### PR TITLE
Add HAProxy PROXY header if configured for upstream handlers

### LINKED ISSUE #13: Supports HAProxy PROXY protocol in handler
It allows to keep the source address over any kind of protocol:

https://www.haproxy.com/blog/haproxy/proxy-protocol/

It is supported for example by Exim:

https://exim.org/exim-html-4.93/doc/html/spec_html/ch-proxies.html

### PR DESCRIPTION
**Pull request by mildred**
Fixes #13

### CODE REVIEW

**Comment by mholt** [comment]
Thank you for the contribution, @mildred ! This actually looks really good. I have to admit I'm not sure yet whether this should be embedded into the proxy like this or whether it should be a separate handler. If there is a use case where a user would like to handle the proxy protocol bytes as part of the connection _before_ proxying, this implementation wouldn't support that... although, I am not sure if that is a real need. I think, other than that, it makes sense to go with this kind of approach.

I'll think on it some more, while inviting further discussion, before reviewing this in more depth. Thanks!

**Comment by francislavoie** [comment]
Related issue in the Caddy project: https://github.com/caddyserver/caddy/issues/2724

**Comment by lxhao61** [comment]
Hope to merge, it works well.

**Review by mholt — APPROVED** [review]
I've thought about it and I think this is good. Thank you! Can you fix up the merge conflict (be sure to test again too) and then we can get this merged?

**Comment by lxhao61** [comment]
Add the following parameters to line 209 in modules/l4proxy/proxy.go:
h.logger.Debug("dial upstream", zap.String("address", hostPort), zap.Error(err))
image
This parameter is additive for [Refactor TLS matcher/handler, and connection recording](https://github.com/mholt/caddy-l4/commit/d1d54b015e34010da10b2f919e8db710c57f7731).

**Comment by mholt** [comment]
Pinging @mildred  -- otherwise, will close for inactivity.

**Comment by mholt** [comment]
Anyone else who wants this is welcome to pick this up and submit the PR without a merge conflict to have it merged.

**Comment by mildred** [comment]
Oops, sorry for the inactivity, I don't read my notifications regularly. I updated my branch with an updated version

**Comment by mholt** [comment]
Awesome! Unfortunately I can't reopen the PR for some reason.

**Comment by mildred** [comment]
I just created a new one

**Pull request closed without merging**
