### PR TITLE
ci: version-ctrl

### PR DESCRIPTION
**Pull request by IceCodeNew**
test against the go version used by the upstream
& the next version of that

### CODE REVIEW

**Comment by IceCodeNew** [comment]
@mholt it seems that the [dependabot](https://github.com/apps/dependabot) is not enabled in this repo. I am wondering if we can let that bot watching the dependencies update for us.
If you are OK with it, please configure the bot to watch both the dependencies of GitHub Action & Go.

**Comment by francislavoie** [comment]
I don't think we really want to do that, we want to keep the go.mod set to the minimum version we support. Really it's now 1.19 as of https://github.com/caddyserver/caddy/commit/8cb1bb4af30b880f981b1ae6fdb13e5944bfaefe.

**Comment by IceCodeNew** [comment]
> I don't think we really want to do that, we want to keep the go.mod set to the minimum version we support. Really it's now 1.19 as of [caddyserver/caddy@8cb1bb4](https://github.com/caddyserver/caddy/commit/8cb1bb4af30b880f981b1ae6fdb13e5944bfaefe).

Fair enough, let's keep on maintaining the matrix of go versions ;-)

**Review by francislavoie — APPROVED** [review]
LGTM

**Comment by francislavoie** [comment]
Re dependabot, you could pull this in https://github.com/caddyserver/caddy/blob/master/.github/dependabot.yml

**Pull request merged**
