### PR TITLE
enable the go test; also set CI for windows & macos

### PR DESCRIPTION
**Pull request by IceCodeNew**

### CODE REVIEW

**Review by mholt — APPROVED** [review]
Cool, let's give it a try! Thanks!

@IceCodeNew Would you like to become a collaborator? Then you can make patches on branches instead of forks. And help review PRs and such. I can't keep up with everything these days and I wouldn't want to be a blocker 😅

**Comment by IceCodeNew** [comment]
> @IceCodeNew Would you like to become a collaborator? Then you can make patches on branches instead of forks. And help review PRs and such. I can't keep up with everything these days and I wouldn't want to be a blocker 😅

It's my honor. Thanks for inviting me ;-)

**Comment by IceCodeNew** [comment]
@mholt I hope this message finds you well. Just want to tell you that this PR is ready for merging. And I am glad to become a collaborator ;-)

**Comment by mholt** [comment]
Perfect, thanks! Welcome to the team!@

**Pull request merged**
