### PR TITLE
introduce the CI

### PR DESCRIPTION
**Pull request by IceCodeNew**
in order to make sure later commits will not break the compilation

### CODE REVIEW

**Comment by ydylla** [comment]
Good idea.
I think the pipeline should also run all tests. You can do this with `go test ./...` this would also have caught the build failure.  

And for the xcaddy build the pipeline should probably use a replacement `--with` to ensure it actually uses the local version of layer4 from the pipeline. You can do this by adding `=.` to the `--with` option (`--with github.com/mholt/caddy-l4=.`).

**Comment by IceCodeNew** [comment]
> Good idea. I think the pipeline should also run all tests. You can do this with `go test ./...` this would also have caught the build failure.
> 
> And for the xcaddy build the pipeline should probably use a replacement `--with` to ensure it actually uses the local version of layer4 from the pipeline. You can do this by adding `=.` to the `--with` option (`--with github.com/mholt/caddy-l4=.`).

Thanks for taking the time to review this PR. I have implemented the amendment ;-)

**Comment by ydylla** [comment]
@IceCodeNew I have fixed the failing test in #86. So I think you can include the tests again, once @mholt merged it.

**Review by mholt — APPROVED** [review]
Awesome!! Thanks for doing this. I admit, I don't have a lot of CI knowledge (most of my energy is focused on the actual code, rather than the releasing of it -- I should probably learn some things though). So I really appreciate this. Let's give this a try.

**Pull request merged**
